export const COMANDOS = [
  { command: 'start', description: 'Menú principal' },
  { command: 'planes', description: 'Ver planes y precios' },
  { command: 'partidos', description: 'Elegir un partido' },
  { command: 'gratis', description: 'Predicción gratis del día' },
  { command: 'mispartidos', description: 'Mis favoritos y alertas PRO' },
  { command: 'estado', description: 'Ver mi acceso' },
  { command: 'pro', description: 'Acceder a PRO' },
  { command: 'analisis', description: 'Abrir un informe: /analisis ID' },
  { command: 'muestra', description: 'Ver ejemplo de informe' },
  { command: 'resultados', description: 'Historial verificable en vivo' },
  { command: 'cancelar', description: 'Cancelar renovación automática' },
  { command: 'terms', description: 'Condiciones de compra' },
  { command: 'paysupport', description: 'Ayuda con compras' },
];
