export const COMANDOS = [
  { command: 'start', description: 'Abrir Monitor eSports' },
  { command: 'planes', description: 'Ver planes y precios' },
  { command: 'partidos', description: 'Elegir un partido' },
  { command: 'gratis', description: 'Predicción FREE del día' },
  { command: 'mios', description: 'Mis partidos y favoritos PRO' },
  { command: 'estado', description: 'Mi plan y configuración' },
  { command: 'pro', description: 'Acceder a PRO' },
  { command: 'analisis', description: 'Abrir un informe: /analisis ID' },
  { command: 'muestra', description: 'Ver ejemplo de informe' },
  { command: 'resultados', description: 'Resultados e historial actualizado' },
  { command: 'cancelar', description: 'Cancelar renovación automática' },
  { command: 'terms', description: 'Condiciones de compra' },
  { command: 'paysupport', description: 'Ayuda con compras' },
];
